version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
    - ./mysqldata:/var/lib/mysql
    ports:
    - 3306:3306

  redis-cluster:
    image: grokzen/redis-cluster:latest
    environment:
      IP: 0.0.0.0
    ports:
      - 7000-7050:7000-7050
      - 5000-5010:5000-5010
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080