# 项目相关配置
project:
  # 名称
  name: cardmerchantfront
  # 版本
  version: 4.1.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /home/a/IdeaProjects/TyPayJV2FinancialFront/uploadPath
  # 获取ip地址开关
  addressEnabled: true


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8584
  servlet:
    # 应用的访问路径
    context-path: /
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.pay.typay: debug
    org.springframework: warn
  config: classpath:logback.xml
  file: ./logs/sys-info.log
# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 3


spring:
  application:
    name: financial-front
  boot:
    admin:
      client:
        url: http://localhost:9898

  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: docker
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.pay.typay.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # SN密钥开关
    googlecodeEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
    https: false
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: false
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: 1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: true

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns: /*


#docker环境
---
# 数据源配置
spring:
  profiles: docker
  topcodetype: googlecode
  #Redis
  redis:
    password:
    timeout: 5000
    jedis:
      pool:
        max-wait: 5000
        max-active: 50
        max-idle: 8
        min-idle: 0
    cluster:
      #节点信息
      nodes: localhost:7001,localhost:7002,localhost:7003
    jpa:
      show-sql: true
    jackson:
      default-property-inclusion: non-null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      cardmerchantfront:
        #本地环境
        #        url: jdbc:mysql://localhost:3306/cardmerchantfront?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        #        username: root
        #        password: root

        #测试环境
        url: jdbc:mysql://8.210.43.213:6980/cardmerchantfront?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: tx_readonly
        password: UusXtTnqaVF4

        #开发环境
      #        url: jdbc:mysql://47.244.108.53:3306/cardmerchantfront?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #        username: admin
      #        password: 97rH3UKuaNeJ5rmJ
      # 从库数据源
      typayv2:
        #本地环境
        #        url: jdbc:mysql://localhost:3306/typayv2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        #        username: root
        #        password: root
        #测试环境
        url: jdbc:mysql://8.210.43.213:6980/typayv2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: tx_readonly
        password: UusXtTnqaVF4
        #开发环境
      #        url: jdbc:mysql://47.244.108.53:3306/typayv2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #        username: admin
      #        password: 97rH3UKuaNeJ5rmJ
      # 从库数据源
      tyadmin:
        #本地环境
        #        url: jdbc:mysql://localhost:3306/tyadmin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        #        username: root
        #        password: root
        #测试环境
        url: jdbc:mysql://8.210.43.213:6980/tyadmin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: tx_readonly
        password: UusXtTnqaVF4
        #开发环境
      #        url: jdbc:mysql:///47.244.108.53:3306/tyadmin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #        username: admin
      #        password: 97rH3UKuaNeJ5rmJ

      # 从库数据源
      typayv2slave:
        #本地环境
        #        url: jdbc:mysql://localhost:3306/typayv2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        #        username: root
        #        password: root

        #测试环境
        url: jdbc:mysql://8.210.43.213:6980/typayv2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: tx_readonly
        password: UusXtTnqaVF4
        #开发环境
      #        url: jdbc:mysql://47.244.108.53:3306/typayv2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #        username: admin
      #        password: 97rH3UKuaNeJ5rmJ

      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
telegram:
  token: 1288935322:AAGQYVc3gDI0BeTZmbATjnRUccB9uOUR168
  chatId: -484607583
  isSendMq: 1

mango:
  userId: cod_60005424
  token: f8f358eb1c5d447a93b3e6299d58ae9a
  roomname: codm_1080005290
  mangoUrl : https://im.imangoim.com:9091/plugins/xhcodrestapi/v1/apiservice/userid:token/v2/sendmessage
#dev环境
---
# 数据源配置
spring:
  profiles: dev
  topcodetype: googlecode
  #Redis
  redis:
    password: guess_guess_101
    timeout: 5000
    jedis:
      pool:
        max-wait: 5000
        max-active: 50
        max-idle: 8
        min-idle: 0
    cluster:
      nodes: 172.16.6.84:7001,172.16.6.84:7002,172.16.6.84:7003
    jpa:
      show-sql: true
    jackson:
      default-property-inclusion: non-null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      cardmerchantfront:
        url: jdbc:mysql://172.16.6.84:3306/cardmerchantfront?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: typay_admin
        password: admin
      # 从库数据源
      typayv2:
        url: jdbc:mysql://172.16.6.84:3306/typayv2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: typay_admin
        password: admin
      # 从库数据源
      tyadmin:
        url: jdbc:mysql://172.16.6.84:3306/tyadmin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: typay_admin
        password: admin
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

#  测试环境
---
spring:
  profiles: fat
  topcodetype: googlecode
  #Redis
  redis:
    password: mWRGi6n91DIkQrSx
    timeout: 5000
    jedis:
      pool:
        max-wait: 5000
        max-active: 50
        max-idle: 8
        min-idle: 0
    cluster:
      nodes: 172.20.21.239:7001,172.20.21.239:7002,172.20.21.239:7003
      #节点信息
      #nodes: typay-redis.typay.svc.cluster.local:6379
    jpa:
      show-sql: true
    jackson:
      default-property-inclusion: non-null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:

      # 主库数据源
      cardmerchantfront:
        url: jdbc:mysql://172.20.21.239:6980/cardmerchantfront?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: tx_devuser
        password: Jz01Qg4axQv.CuZj
      # 从库数据源
      typayv2:
        url: jdbc:mysql:/172.20.21.239:6980/typayv2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: tx_devuser
        password: Jz01Qg4axQv.CuZj
      # 从库数据源
      tyadmin:
        url: jdbc:mysql://172.20.21.239:6980/tyadmin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: tx_devuser
        password: Jz01Qg4axQv.CuZj

      # 从库数据源
      typayv2slave:
        url: jdbc:mysql://172.20.21.239:6980/typayv2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: tx_devuser
        password: Jz01Qg4axQv.CuZj

      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
telegram:
  token: 1288935322:AAGQYVc3gDI0BeTZmbATjnRUccB9uOUR168
  chatId: -484607583
  isSendMq: 1

#  uat环境
---
spring:
  profiles: uat
  topcodetype: googlecode
  #Redis
  redis:
    password: fySg56cNX9
    timeout: 5000
    jedis:
      pool:
        max-wait: 5000
        max-active: 50
        max-idle: 8
        min-idle: 0
    cluster:
      nodes: 10.4.17.220:7001,10.4.17.220:7002,10.4.17.221:7001,10.4.17.221:7002,10.4.17.222:7001,10.4.17.222:7002
      #节点信息
      #nodes: typay-redis.typay.svc.cluster.local:6379
    jpa:
      show-sql: true
    jackson:
      default-property-inclusion: non-null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      cardmerchantfront:
        url: jdbc:mysql://w_txdb.service.kk:6003/cardmerchantfront?useUnicode=true&characterEncoding=UTF-8
        username: typay_admin
        password: R9xsHwbVH8upwT1d
      # 从库数据源
      typayv2:
        url: jdbc:mysql://w_txdb.service.kk:6003/typayv2?useUnicode=true&characterEncoding=UTF-8
        username: typay_admin
        password: R9xsHwbVH8upwT1d
      # 从库数据源
      tyadmin:
        url: jdbc:mysql://w_txdb.service.kk:6003/tyadmin?useUnicode=true&characterEncoding=UTF-8
        username: typay_admin
        password: R9xsHwbVH8upwT1d

      # 从库数据源
      typayv2slave:
        url: jdbc:mysql://r_txdb.service.kk:6003/typayv2?useUnicode=true&characterEncoding=UTF-8
        username: typay_admin
        password: R9xsHwbVH8upwT1d
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
#  prod环境
---
spring:
  profiles: prod
  topcodetype: googlecode
  #Redis
  redis:
    password: fySg56cNX9
    timeout: 5000
    jedis:
      pool:
        max-wait: 5000
        max-active: 50
        max-idle: 8
        min-idle: 0
    cluster:
      nodes: 10.4.17.220:7001,10.4.17.220:7002,10.4.17.221:7001,10.4.17.221:7002,10.4.17.222:7001,10.4.17.222:7002
      #节点信息
      #nodes: typay-redis.typay.svc.cluster.local:6379
    jpa:
      show-sql: true
    jackson:
      default-property-inclusion: non-null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      cardmerchantfront:
        url: jdbc:mysql://w_txdb.service.kk:6003/cardmerchantfront?useUnicode=true&characterEncoding=UTF-8
        username: typay_admin
        password: R9xsHwbVH8upwT1d
      # 从库数据源
      typayv2:
        url: jdbc:mysql://w_txdb.service.kk:6003/typayv2?useUnicode=true&characterEncoding=UTF-8
        username: typay_admin
        password: R9xsHwbVH8upwT1d
      # 从库数据源
      tyadmin:
        url: jdbc:mysql://w_txdb.service.kk:6003/tyadmin?useUnicode=true&characterEncoding=UTF-8
        username: typay_admin
        password: R9xsHwbVH8upwT1d

      # 从库数据源
      typayv2slave:
        url: jdbc:mysql://r_txdb.service.kk:6003/typayv2?useUnicode=true&characterEncoding=UTF-8
        username: typay_admin
        password: R9xsHwbVH8upwT1d

      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true


